services:
  postgres:
    image: postgres:17
    container_name: goque-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: goque
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  apply-postgres-migrations:
    image: kukymbr/goose-docker:3.26.0
    container_name: postgres-migrations
    environment:
      GOOSE_DBSTRING: 'postgres://postgres:postgres@postgres:5432/postgres?sslmode=disable'
      GOOSE_DRIVER: postgres
    volumes:
      - ./migrations/pg:/migrations:ro
    depends_on:
      postgres:
        condition: service_healthy

  mysql:
    image: mysql:8
    container_name: goque-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goque
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5

  apply-mysql-migrations:
    image: kukymbr/goose-docker:3.26.0
    container_name: mysql-migrations
    environment:
      GOOSE_DBSTRING: 'root:root@tcp(mysql:3306)/goque?parseTime=true'
      GOOSE_DRIVER: mysql
    volumes:
      - ./migrations/mysql:/migrations:ro
    depends_on:
      mysql:
        condition: service_healthy
